### ISSUE TITLE
signkey error "ios development"

### ISSUE THREAD

**Issue by pl4ten** [MohamadKh75/iOS_Development_Certificates#30]
hi
I have a problem with this section
i tested :
```
[+] delete profile 
[+] re login to apple id and get certification
[+] delete all key chain an re add all certification
```

![VirtualBox_w2_03_12_2022_15_11_04](https://user-images.githubusercontent.com/50620571/205439204-04f305ac-6d82-476d-b275-069fe0165796.png)

any advice :)  ?

**Comment by mahadshahib** [comment]
> hi I have a problem with this section i tested :
> 
> ```
> [+] delete profile 
> [+] re login to apple id and get certification
> [+] delete all key chain an re add all certification
> ```
> 
> ![VirtualBox_w2_03_12_2022_15_11_04](https://user-images.githubusercontent.com/50620571/205439204-04f305ac-6d82-476d-b275-069fe0165796.png)
> 
> any advice :) ?

**Comment by mahadshahib** [comment]
> hi I have a problem with this section i tested :
> 
> ```
> [+] delete profile 
> [+] re login to apple id and get certification
> [+] delete all key chain an re add all certification
> ```
> 
> ![VirtualBox_w2_03_12_2022_15_11_04](https://user-images.githubusercontent.com/50620571/205439204-04f305ac-6d82-476d-b275-069fe0165796.png)
> 
> any advice :) ?

It is probably because of your code signing identity of your project which you can find it under build settings in Xcode; it should be iOS Distribution under iOS SDK (if you cannot find iOS SDK, you should expand Code Signing Identity section). And then try again WITH THE NEW Bundle Identifier that I mentioned in ReadMe.md. Let me know if your problem still exists after these changes.
